# WebSocket connection parameters
occupancy:
  url: "wss://badi-public.crowdmonitor.ch:9591/api"
  retry_interval_seconds: 30
  timeout_seconds: 10
  ping_interval_seconds: 20
  ping_timeout_seconds: 10

# Temperature data collection parameters
temperature:
  url: "https://www.stadt-zuerich.ch/stzh/bathdatadownload"
  poll_interval_seconds: 3600  # 1 hour
  timeout_seconds: 30

# Prometheus metrics
metrics:
  port: 8000
  endpoint: "/metrics"
  namespace: "zurich_pools"

# Pools to monitor (can add/remove as needed)
pools:
  - uid: "flb6939"
    name: "Flussbad Oberer Letten"
  - uid: "flb6940"
    name: "Flussbad Unterer Letten"
  - uid: "flb8803"
    name: "Flussbad Unterer Letten (Flussteil)"
  - uid: "flb6941"
    name: "Frauenbad Stadthausquai"
  - uid: "fb006"
    name: "Freibad Allenmoos"
  - uid: "fb008"
    name: "Freibad Auhof"
  - uid: "fb012"
    name: "Freibad Heuried"
  - uid: "SSD-11"
    alt_uid: "fb013"
    name: "Freibad Seebach"
  - uid: "fb018"
    name: "Freibad Zwischen den Hölzern"
  - uid: "SSD-1"
    name: "Hallenbad Altstetten"
  - uid: "SSD-2"
    name: "Hallenbad Blaesi"
    hardcoded_temperatur: 29
  - uid: "SSD-3"
    name: "Hallenbad Bungertwies"
    hardcoded_temperatur: 29
  - uid: "SSD-4"
    name: "Hallenbad City"
    hardcoded_temperatur: 28
  - uid: "SSD-6"
    alt_uid: "hb006"
    name: "Hallenbad Leimbach"
    hardcoded_temperatur: 29
  - uid: "SSD-7"
    name: "Hallenbad Oerlikon"
    hardcoded_temperatur: 28
  - uid: "SSD-8"
    name: "Josel-Areal"
  - uid: "SSD-10"
    alt_uid: "seb6945"
    name: "Seebad Utoquai"
  - uid: "SSD-5"
    name: "Waermebad Kaeferberg"
    hardcoded_temperatur: 32
  - uid: "seb6946"
    name: "Strandbad Mythenquai"
  - uid: "seb6947"
    name: "Strandbad Tiefenbrunnen"
  - uid: "seb6948"
    name: "Strandbad Wollishofen"
  - uid: "BADI-1"
    alt_uid: "seb6943"
    name: "Seebad Enge"

# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
