{
 "title": "Badis",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "pool", "label": "Pool Name", "query": { "query": "label_values(pool_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Occupancy",
   "type": "gauge",
   "description": "Compared to the maximum value measured over the past 90 days.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zurich_pools_current_fill{pool_name=~\"$pool\"}",
     "legendFormat": "{{pool_name}}"
    },
    {
     "expr": "max_over_time(zurich_pools_current_fill{pool_name=~\"$pool\"}[90d])",
     "legendFormat": "{{pool_name}}"
    },
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Current Visitor Count",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zurich_pools_current_fill{pool_name=~\"$pool\"}",
     "legendFormat": "{{pool_name}}"
    }
   ]
  },
  {
   "title": "Water Temperature",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zurich_pools_water_temperature{pool_name=~\"$pool\"}",
     "legendFormat": "{{pool_name}}"
    }
   ]
  },
  {
   "title": "Fill Difference",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "zurich_pools_current_fill{pool_name=~\"$pool\"}",
     "legendFormat": "{{pool_name}}"
    }
   ]
  },
  {
   "title": "Current Fill",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "zurich_pools_current_fill{pool_name=~\"$pool\"}",
     "legendFormat": "{{pool_name}}"
    }
   ]
  },
  {
   "title": "Current Fill Ratio Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "zurich_pools_current_fill{pool_name=~\"$pool\"} / ignoring(instance,job) max_over_time(zurich_pools_current_fill{pool_name=~\"$pool\"}[90d])",
     "legendFormat": "{{pool_name}}"
    }
   ]
  },
  {
   "title": "Water Temperature",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "zurich_pools_water_temperature{pool_name=~\"$pool\"}",
     "legendFormat": "{{pool_name}}"
    }
   ]
  }
 ]
}