# WebSocket connection parameters
websocket:
  url: "wss://badi-public.crowdmonitor.ch:9591/api"
  retry_interval_seconds: 30
  timeout_seconds: 10
  ping_interval_seconds: 20
  ping_timeout_seconds: 10

# Prometheus metrics
metrics:
  port: 8000
  endpoint: "/metrics"
  namespace: "zurich_pools"

# Pools to monitor (can add/remove as needed)
pools:
  - uid: "flb6939"
    name: "Flussbad Oberer Letten"
  - uid: "flb6940"
    name: "Flussbad Unterer Letten"
  - uid: "flb8803"
    name: "Flussbad Unterer Letten (Flussteil)"
  - uid: "flb6941"
    name: "Frauenbad Stadthausquai"
  - uid: "fb006"
    name: "Freibad Allenmoos"
  - uid: "fb008"
    name: "Freibad Auhof"
  - uid: "fb012"
    name: "Freibad Heuried"
  - uid: "SSD-11"
    name: "Freibad Seebach"
  - uid: "fb018"
    name: "Freibad Zwischen den Hölzern"
  - uid: "SSD-1"
    name: "Hallenbad Altstetten"
  - uid: "SSD-2"
    name: "Hallenbad Blaesi"
  - uid: "SSD-3"
    name: "Hallenbad Bungertwies"
  - uid: "SSD-4"
    name: "Hallenbad City"
  - uid: "SSD-6"
    name: "Hallenbad Leimbach"
  - uid: "SSD-7"
    name: "Hallenbad Oerlikon"
  - uid: "SSD-8"
    name: "Josel-Areal"
  - uid: "SSD-10"
    name: "Seebad Utoquai"
  - uid: "SSD-5"
    name: "Waermebad Kaeferberg"

# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
